using System.Collections.Generic;
using UnityEngine;

namespace DotRPG
{
    /// <summary>
    /// Resolves sprite keys to Sprites.
    /// 1. If Resources/Art/{key} exists (a PNG imported as Sprite), that asset is used.
    /// 2. Otherwise the placeholder is generated by <see cref="ProceduralArt"/> and cached.
    /// This is the single seam for swapping in final art: artists drop files in with matching
    /// names and no code changes are needed. Keys are listed in Docs/ART_KEYS.md.
    /// </summary>
    public sealed class SpriteLibrary
    {
        public const string OverrideFolder = "Art/";

        readonly int pixelsPerUnit;
        readonly Dictionary<string, Sprite> cache = new Dictionary<string, Sprite>();

        public SpriteLibrary(int pixelsPerUnit)
        {
            this.pixelsPerUnit = pixelsPerUnit;
        }

        public int PixelsPerUnit => pixelsPerUnit;

        public Sprite Get(string key)
        {
            if (cache.TryGetValue(key, out var sprite)) return sprite;

            sprite = Resources.Load<Sprite>(OverrideFolder + key);
            if (sprite == null)
            {
                var canvas = ProceduralArt.Draw(key);
                sprite = canvas != null ? ToSprite(key, canvas) : Missing(key);
            }
            cache[key] = sprite;
            return sprite;
        }

        /// <summary>Character frame. dir: down/up/side. frame: idle0, idle1, walk0-3, attack, hurt.</summary>
        public Sprite GetCharacter(CharacterLook look, string dir, string frame)
        {
            string key = $"char_{look.id}_{dir}_{frame}";
            if (cache.TryGetValue(key, out var sprite)) return sprite;
            sprite = Resources.Load<Sprite>(OverrideFolder + key);
            if (sprite == null) sprite = ToSprite(key, ProceduralArt.DrawCharacter(look, dir, frame));
            cache[key] = sprite;
            return sprite;
        }

        Sprite ToSprite(string key, PixelCanvas canvas)
        {
            var texture = new Texture2D(canvas.Width, canvas.Height, TextureFormat.RGBA32, false)
            {
                name = key,
                filterMode = FilterMode.Point,
                wrapMode = TextureWrapMode.Clamp,
            };
            texture.SetPixels32(canvas.ToTexturePixels());
            // Kept readable so hit-flash silhouettes can be derived from it.
            texture.Apply(false, false);

            var pivot = new Vector2(canvas.PivotX / canvas.Width, canvas.PivotY / canvas.Height);
            var border = new Vector4(canvas.BorderLeft, canvas.BorderBottom, canvas.BorderRight, canvas.BorderTop);
            var sprite = Sprite.Create(texture, new Rect(0, 0, canvas.Width, canvas.Height), pivot, pixelsPerUnit, 0,
                SpriteMeshType.FullRect, border);
            sprite.name = key;
            return sprite;
        }

        readonly Dictionary<Sprite, Sprite> silhouettes = new Dictionary<Sprite, Sprite>();

        /// <summary>
        /// Solid white copy of a sprite, used for the classic "hit flash" without custom shaders.
        /// Returns null when the source texture is not CPU-readable (enable Read/Write on imported art).
        /// </summary>
        public Sprite GetSilhouette(Sprite source)
        {
            if (source == null) return null;
            if (silhouettes.TryGetValue(source, out var cached)) return cached;

            Sprite result = null;
            var texture = source.texture;
            if (texture != null && texture.isReadable)
            {
                var rect = source.textureRect;
                int x = Mathf.RoundToInt(rect.x), y = Mathf.RoundToInt(rect.y);
                int w = Mathf.RoundToInt(rect.width), h = Mathf.RoundToInt(rect.height);
                var pixels = texture.GetPixels(x, y, w, h);
                for (int i = 0; i < pixels.Length; i++) pixels[i] = new Color(1f, 1f, 1f, pixels[i].a);
                var white = new Texture2D(w, h, TextureFormat.RGBA32, false)
                {
                    name = source.name + "_flash",
                    filterMode = FilterMode.Point,
                    wrapMode = TextureWrapMode.Clamp,
                };
                white.SetPixels(pixels);
                white.Apply(false, true);
                var pivot = new Vector2(source.pivot.x / w, source.pivot.y / h);
                result = Sprite.Create(white, new Rect(0, 0, w, h), pivot, source.pixelsPerUnit, 0, SpriteMeshType.FullRect);
                result.name = white.name;
            }
            silhouettes[source] = result;
            return result;
        }

        Sprite Missing(string key)
        {
            Debug.LogWarning($"[dotRPG] No sprite for key '{key}'. Add Resources/{OverrideFolder}{key}.png or a ProceduralArt case.");
            var canvas = new PixelCanvas(8, 8);
            canvas.Rect(0, 0, 8, 8, new Color32(255, 0, 255, 255));
            return ToSprite(key, canvas);
        }
    }
}
