using System.Collections.Generic;
using UnityEngine;

namespace DotRPG
{
    /// <summary>
    /// Resolves sprite keys to Sprites.
    /// 1. If Resources/Art/{key} exists (a PNG imported as Sprite), that asset is used.
    /// 2. Otherwise the placeholder is generated by <see cref="ProceduralArt"/> and cached.
    /// This is the single seam for swapping in final art: artists drop files in with matching
    /// names and no code changes are needed. Keys are listed in Docs/ART_KEYS.md.
    /// </summary>
    public sealed class SpriteLibrary
    {
        public const string OverrideFolder = "Art/";

        readonly int pixelsPerUnit;
        readonly Dictionary<string, Sprite> cache = new Dictionary<string, Sprite>();

        public SpriteLibrary(int pixelsPerUnit)
        {
            this.pixelsPerUnit = pixelsPerUnit;
        }

        public int PixelsPerUnit => pixelsPerUnit;

        public Sprite Get(string key)
        {
            if (cache.TryGetValue(key, out var sprite)) return sprite;

            // [GEAR] "gear:<id>": the item's own icon (Art/Gear/eqicon_<id>) once drawn, else the old icon of its tier band.
            if (key.StartsWith("gear:"))
            {
                string id = key.Substring(5);
                sprite = Resources.Load<Sprite>(OverrideFolder + "Gear/eqicon_" + id);
                if (sprite == null) sprite = Get(EquipmentDatabase.Get(id)?.fallbackIcon ?? "icon_chest");
                cache[key] = sprite;
                return sprite;
            }

            // Redrawn weapons (held staffs and weapon icons) live in Art/Weapons and win over the old art.
            if (key.StartsWith("wpn_") || key.StartsWith("eqicon_")) sprite = Resources.Load<Sprite>(OverrideFolder + "Weapons/" + key);
            sprite = sprite ?? CareerMoves.Icon(key) ?? WinterVillageArt.Get(key) ?? Resources.Load<Sprite>(OverrideFolder + key);
            var building = VillageBuildingArt.Find(key);
            if (sprite == null && building != null) sprite = Resources.Load<Sprite>(building.ResourcePath);
            var nature = VillageNatureArt.Find(key);
            if (sprite == null && nature != null) sprite = Resources.Load<Sprite>(nature.ResourcePath);
            if (sprite == null && KatanaArt.Handles(key)) sprite = KatanaArt.Get(key);
            if (sprite == null)
            {
                var canvas = ProceduralArt.Draw(key);
                sprite = canvas != null ? ToSprite(key, canvas) : Missing(key);
            }
            cache[key] = sprite;
            return sprite;
        }

        /// <summary>Character frame. dir: down/up/side. frame: idle0, idle1, walk0-3, attack, hurt.</summary>
        static readonly System.Text.RegularExpressions.Regex GearSuffix = new System.Text.RegularExpressions.Regex(@"_t-?\d+_b-?\d+$");

        public Sprite GetCharacter(CharacterLook look, string dir, string frame)
        {
            string key = $"char_{look.id}_{dir}_{frame}";
            if (cache.TryGetValue(key, out var sprite)) return sprite;
            sprite = RegionalMonsterArt.Get(look.id, dir, frame) ?? Resources.Load<Sprite>(OverrideFolder + key);
            // [ART] Generated character frames are per base look: a geared look ("mage_t1_b0") uses its base's.
            if (sprite == null)
            {
                string baseId = GearSuffix.Replace(look.id, "");
                if (baseId != look.id) sprite = Resources.Load<Sprite>($"{OverrideFolder}char_{baseId}_{dir}_{frame}");
            }
            if (sprite == null && SilverWarriorArt.Supports(look.id)) sprite = SilverWarriorArt.Get(look, dir, frame);
            if (sprite == null) sprite = ToSprite(key, ProceduralArt.DrawCharacter(look, dir, frame));
            cache[key] = sprite;
            return sprite;
        }

        /// <summary>Katana for the equipped tier, pivoted at the right-hand grip.</summary>
        public Sprite GetWarriorWeapon(string itemId)
        {
            var item = EquipmentDatabase.Get(itemId);
            if (item == null || item.category != EquipCategory.Weapon || !item.UsableBy(CharacterClass.Warrior)) return null;
            string key = "silver_held_" + itemId;
            if (cache.TryGetValue(key, out var ready)) return ready;
            var original = Get(EquipmentDatabase.WeaponSprite(itemId, CharacterClass.Warrior));
            var result = Sprite.Create(original.texture, original.rect, new Vector2(.5f, KatanaArt.GripY / original.rect.height), original.pixelsPerUnit, 0, SpriteMeshType.FullRect);
            result.name = key; cache[key] = result;
            return result;
        }

        Sprite ToSprite(string key, PixelCanvas canvas)
        {
            // High-resolution art (density 2) is drawn through the sharp-scaling material, which needs
            // bilinear sampling; everything else stays point-filtered.
            bool hd = canvas.Density > 1;
            // Skill effects use the plain sprite materials, so their high-resolution art stays point-filtered (crisp pixels).
            bool smooth = key == "fx_glow" || (hd && FxMaterials.Sharp != null && !key.StartsWith("fx_"));
            var texture = new Texture2D(canvas.Width, canvas.Height, TextureFormat.RGBA32, false)
            {
                name = key,
                // Soft light is blown up to many times its size, so it is the one sprite drawn smooth.
                filterMode = smooth ? FilterMode.Bilinear : FilterMode.Point,
                wrapMode = TextureWrapMode.Clamp,
            };
            var pixels = canvas.ToTexturePixels();
            if (hd && smooth) BleedTransparent(pixels, canvas.Width, canvas.Height);
            texture.SetPixels32(pixels);
            // Kept readable so hit-flash silhouettes can be derived from it.
            texture.Apply(false, false);

            var pivot = new Vector2(canvas.PivotX / canvas.Width, canvas.PivotY / canvas.Height);
            var border = new Vector4(canvas.BorderLeft, canvas.BorderBottom, canvas.BorderRight, canvas.BorderTop);
            var sprite = Sprite.Create(texture, new Rect(0, 0, canvas.Width, canvas.Height), pivot, pixelsPerUnit * Mathf.Max(1, canvas.Density), 0,
                SpriteMeshType.FullRect, border);
            sprite.name = key;
            return sprite;
        }

        /// <summary>
        /// Gives fully transparent pixels next to the artwork the colour of their opaque neighbours
        /// (alpha stays 0). Bilinear sampling at a sprite's silhouette then blends towards the right
        /// colour instead of towards black, so no dark fringe appears.
        /// </summary>
        static void BleedTransparent(Color32[] px, int w, int h)
        {
            var known = new bool[px.Length];
            for (int i = 0; i < px.Length; i++) known[i] = px[i].a > 0;
            for (int pass = 0; pass < 2; pass++)
            {
                var next = (bool[])known.Clone();
                for (int y = 0; y < h; y++)
                    for (int x = 0; x < w; x++)
                    {
                        int i = y * w + x;
                        if (known[i]) continue;
                        int r = 0, g = 0, b = 0, n = 0;
                        for (int dy = -1; dy <= 1; dy++)
                            for (int dx = -1; dx <= 1; dx++)
                            {
                                int xx = x + dx, yy = y + dy;
                                if (xx < 0 || yy < 0 || xx >= w || yy >= h) continue;
                                int j = yy * w + xx;
                                if (!known[j]) continue;
                                r += px[j].r; g += px[j].g; b += px[j].b; n++;
                            }
                        if (n == 0) continue;
                        px[i] = new Color32((byte)(r / n), (byte)(g / n), (byte)(b / n), 0);
                        next[i] = true;
                    }
                known = next;
            }
        }

        /// <summary>
        /// Wraps an already painted, opaque pixel block (rows bottom-up, Unity order) in a sprite with
        /// its pivot at the bottom-left corner. Used for the painted ground of the high-resolution maps.
        /// The caller owns the result (it is not cached by key).
        /// </summary>
        public Sprite CreateRaw(string name, Color32[] bottomUpPixels, int width, int height, int density)
        {
            bool smooth = density > 1 && FxMaterials.Sharp != null;
            var texture = new Texture2D(width, height, TextureFormat.RGBA32, false)
            {
                name = name,
                filterMode = smooth ? FilterMode.Bilinear : FilterMode.Point,
                wrapMode = TextureWrapMode.Clamp,
            };
            texture.SetPixels32(bottomUpPixels);
            texture.Apply(false, true);
            var sprite = Sprite.Create(texture, new Rect(0, 0, width, height), Vector2.zero, pixelsPerUnit * Mathf.Max(1, density), 0, SpriteMeshType.FullRect);
            sprite.name = name;
            return sprite;
        }

        readonly Dictionary<Sprite, Sprite> silhouettes = new Dictionary<Sprite, Sprite>();

        /// <summary>
        /// Solid white copy of a sprite, used for the classic "hit flash" without custom shaders.
        /// Returns null when the source texture is not CPU-readable (enable Read/Write on imported art).
        /// </summary>
        public Sprite GetSilhouette(Sprite source)
        {
            if (source == null) return null;
            if (silhouettes.TryGetValue(source, out var cached)) return cached;

            Sprite result = null;
            var texture = source.texture;
            if (texture != null && texture.isReadable)
            {
                var rect = source.textureRect;
                int x = Mathf.RoundToInt(rect.x), y = Mathf.RoundToInt(rect.y);
                int w = Mathf.RoundToInt(rect.width), h = Mathf.RoundToInt(rect.height);
                var pixels = texture.GetPixels(x, y, w, h);
                for (int i = 0; i < pixels.Length; i++) pixels[i] = new Color(1f, 1f, 1f, pixels[i].a);
                var white = new Texture2D(w, h, TextureFormat.RGBA32, false)
                {
                    name = source.name + "_flash",
                    filterMode = FilterMode.Point,
                    wrapMode = TextureWrapMode.Clamp,
                };
                white.SetPixels(pixels);
                white.Apply(false, true);
                var pivot = new Vector2(source.pivot.x / w, source.pivot.y / h);
                result = Sprite.Create(white, new Rect(0, 0, w, h), pivot, source.pixelsPerUnit, 0, SpriteMeshType.FullRect);
                result.name = white.name;
            }
            silhouettes[source] = result;
            return result;
        }

        Sprite Missing(string key)
        {
            Debug.LogWarning($"[dotRPG] No sprite for key '{key}'. Add Resources/{OverrideFolder}{key}.png or a ProceduralArt case.");
            var canvas = new PixelCanvas(8, 8);
            canvas.Rect(0, 0, 8, 8, new Color32(255, 0, 255, 255));
            return ToSprite(key, canvas);
        }
    }
}
