# -*- coding: utf-8 -*-
"""Chapter 1 quests, cutscenes and world placements (Docs/STORY.md section 4)."""
N = "{name}"

def obj(type, target, count=1, text="", dialogue="", consume=False, map=""):
    return {"type": type, "target": target, "count": count, "text": text, "dialogue": dialogue, "consume": consume, "map": map}

def step(text, objectives, cutscene="", flags=()):
    return {"text": text, "objectives": objectives, "cutscene": cutscene, "setFlags": list(flags)}

def quest(id, code, title, summary, steps, kind="main", requires=(), flags=(), minLevel=0, giver="", offer="",
          turnIn="", turnInDialogue="", start="", reward=None, chapter=1):
    r = {"xp": 0, "gold": 0, "items": [], "maxHealth": 0, "setFlags": []}
    r.update(reward or {})
    return {"id": id, "chapter": chapter, "kind": kind, "code": code, "title": title, "summary": summary,
            "requires": list(requires), "requiresFlags": list(flags), "minLevel": minLevel, "giver": giver,
            "offerDialogue": offer, "turnIn": turnIn, "turnInDialogue": turnInDialogue, "startCutscene": start,
            "steps": steps, "reward": r}

def items(*pairs):
    return [{"id": i, "count": c} for i, c in pairs]

CHAPTER = {"number": 1, "title": "잿더미의 마굿간",
           "summary": "해골 숲 옆 작은 마을의 마굿간에서 자란 아이. 축제 전날 밤, 모든 것을 잃는다."}

QUESTS = [
    quest("c1_morning", "1-1", "마굿간의 아침",
          "브람의 마굿간에서 맞는 평범한 아침. 밤톨에게 여물을 주고, 한나의 아침을 먹고, 리아를 만나자.",
          [step("브람 아저씨가 깨운다.", [obj("cutscene", "c1_intro", map="village", text="마굿간에서 눈을 뜬다")]),
           step("밤톨을 돌본다.", [obj("interact", "feed_horse", text="밤톨에게 여물 주기", map="village"),
                                  obj("interact", "fill_trough", text="물통 채우기", map="village")]),
           step("한나 아주머니가 아침을 차려 두었다.", [obj("talk", "hanna", dialogue="c1_hanna_breakfast", text="한나와 아침 먹기")]),
           step("리아가 찾고 있었다.", [obj("talk", "ria", dialogue="c1_ria_promise", text="리아 만나기")])],
          reward={"xp": 20, "setFlags": ["festival_eve"]}),
    quest("c1_festival", "1-2", "축제 전야",
          "내일은 용사의 봉인을 기리는 등불 축제. 한나의 심부름으로 마을을 한 바퀴 돈다.",
          [step("한나의 심부름: 등불 기름, 당근, 등불.", [
              obj("talk", "merchant", dialogue="c1_errand_merchant", text="잡화상인 미르에게 등불 기름 받기"),
              obj("talk", "farmer", dialogue="c1_errand_farmer", text="농부 하나에게 당근 받기"),
              obj("talk", "chief", dialogue="c1_errand_chief", text="촌장 모리에게 등불 받기")]),
           step("심부름 끝. 마굿간으로 돌아간다.", [obj("talk", "hanna", dialogue="c1_hanna_errand_done", text="한나에게 돌아가기")]),
           step("리아가 마굿간 옆에서 기다린다.", [obj("talk", "ria", dialogue="c1_ria_ribbon", text="리아 만나기")])],
          requires=["c1_morning"], giver="hanna", offer="c1_hanna_errand",
          reward={"xp": 40, "setFlags": ["ribbon_given"]}),
    quest("c1_burning", "1-3", "불타는 밤",
          "축제의 밤. 해골 숲에서 언데드가 쏟아졌다.",
          [step("축제의 밤.", [obj("cutscene", "c1_attack", map="village", text="등불 축제")]),
           step("광장에 해골이 몰려온다. 리아를 지켜라!", [obj("kill", "skel_warrior", 5, text="광장의 해골 쓰러뜨리기")],
                cutscene="c1_stable")],
          requires=["c1_festival"], start="", reward={"xp": 60}),
    quest("c1_ashes", "1-4", "잿더미",
          "사흘 뒤. 마굿간은 재만 남았다.",
          [step("눈을 뜬다.", [obj("cutscene", "c1_wake", map="village", text="사흘 뒤")]),
           step("마굿간 옆 무덤.", [obj("interact", "family_graves", text="브람과 한나의 무덤 앞에 서기", map="village")],
                cutscene="c1_graves")],
          requires=["c1_burning"], reward={"xp": 30}),
    quest("c1_rise", "1-5", "다시 일어서기",
          "카엘에게 싸우는 법을 배운다. 강해져야 리아를 되찾는다.",
          [step("해골 숲 어귀의 해골 세 마리.", [obj("kill", "skeleton", 3, text="해골 숲의 해골 쓰러뜨리기", map="forest")]),
           step("카엘에게 돌아간다.", [obj("talk", "kael", dialogue="c1_kael_training_done", text="카엘에게 돌아가기")])],
          requires=["c1_ashes"], giver="kael", offer="c1_kael_training_offer",
          reward={"xp": 120, "gold": 300, "items": items(("potion_hp", 5))}),
    quest("c1_rebuild", "1-6", "마을 복구",
          "불탄 공방을 다시 세운다. 집을 고칠 연장부터 만들어야 마을이 산다.",
          [step("재료를 모아 공사장에 전달하고, 해골을 쫓아낸다.", [
              obj("flag", "workshop_built", text="공방 재건 (목재·돌을 동쪽 공사장에 전달)"),
              obj("kill", "skeleton", 3, text="해골 퇴치", map="forest")])],
          requires=["c1_rise"], giver="chief", offer="chief_intro", turnIn="chief", turnInDialogue="chief_report",
          reward={"xp": 200, "maxHealth": 20, "items": items(("eq_ring_ruby", 1))}),
    quest("c1_trail", "1-7", "해골 숲의 흔적",
          "놈들은 해골 숲을 지나 북쪽으로 빠졌다. 흔적을 찾아라.",
          [step("해골 숲 북쪽 옛 묘지.", [obj("interact", "ria_ribbon", text="옛 묘지 근처에서 흔적 찾기", map="forest")]),
           step("카엘에게 알린다.", [obj("talk", "kael", dialogue="c1_kael_trail_report", text="카엘에게 보여 주기")])],
          requires=["c1_rebuild"], giver="kael", offer="c1_kael_trail_offer", reward={"xp": 250}),
    quest("c1_stronger", "1-8", "강해져야 한다",
          "지금으로는 북쪽 고개 성채 문턱도 넘지 못한다. 요일 던전에서 실력을 쌓아라.",
          [step("요일 던전에서 싸움을 몸에 새긴다.", [obj("dungeon", "*", 10, text="요일 던전 클리어"),
                                                    obj("level", "", 16, text="레벨 16 달성")])],
          requires=["c1_trail"], giver="kael", offer="c1_kael_stronger_offer", turnIn="kael", turnInDialogue="c1_kael_stronger_report",
          reward={"xp": 600, "gold": 3000}),
    quest("c1_fortress", "1-9", "북쪽 고개 성채",
          "해골왕의 성채. 성문은 수요일, 토요일, 일요일에만 열린다. (중간 레이드)",
          [step("해골왕을 쓰러뜨린다.", [obj("raid", "raid_skeleton_king", text="레이드: 해골왕 클리어")])],
          requires=["c1_stronger"], giver="kael", offer="c1_kael_fortress_offer", turnIn="kael", turnInDialogue="c1_kael_fortress_report",
          reward={"xp": 1500, "gold": 8000}),
    quest("c1_bargas", "1-10", "흑철의 바르가스",
          "봉인 열쇠 조각을 모아 흑철 진영으로. 마을을 불태운 그 갑옷. (최종 레이드, 일요일)",
          [step("흑철 진영의 바르가스를 쓰러뜨린다.", [obj("raid", "raid_bargas", text="레이드: 흑철의 바르가스 클리어")]),
           step("진영에서 돌아온다.", [obj("cutscene", "c1_bargas_end", map="village", text="마을로 돌아가기")])],
          requires=["c1_fortress"], giver="kael", offer="c1_kael_fortress_report_followup", turnIn="chief", turnInDialogue="c1_bargas_report",
          reward={"xp": 3000, "gold": 15000}),
    quest("c1_road", "1-끝", "길 위로",
          "리아는 협곡 너머로 옮겨졌다. 마을을 떠날 시간이다.",
          [step("무덤에 인사를 한다.", [obj("cutscene", "c1_departure", map="village", text="떠나기 전에")])],
          requires=["c1_bargas"], reward={"xp": 500, "setFlags": ["chapter1_done"]}),
    # ---------------- 서브 ----------------
    quest("c1s_horse", "", "밤톨을 찾아서",
          "그날 밤 숲으로 달아난 밤톨. 숲 남쪽 연못가를 찾아본다.",
          [step("숲 남쪽 연못가.", [obj("interact", "lost_horse", text="해골 숲 남쪽 연못가에서 밤톨 찾기", map="forest")])],
          kind="sub", requires=["c1_rise"], giver="herbalist", offer="c1s_horse_offer", turnIn="herbalist", turnInDialogue="c1s_horse_report",
          reward={"xp": 150, "gold": 500, "setFlags": ["horse_back"]}),
    quest("c1s_herbs", "", "리아의 약초밭",
          "리아가 가꾸던 약초밭의 울타리가 타 버렸다.",
          [step("목재를 모은다.", [obj("collect", "wood", 5, text="목재", consume=True)])],
          kind="sub", requires=["c1_rise"], giver="herbalist", offer="c1s_herbs_offer", turnIn="herbalist", turnInDialogue="c1s_herbs_report",
          reward={"xp": 120, "items": items(("potion_hp", 8), ("potion_mp", 5))}),
]

# Village map-text cells: stable 'L' anchors at (5,11) [cols 5-14, rows 4-11], door ~ (10,12). Plaza fountain (27,33).
WORLD = {
    "placements": [
        {"npcId": "bram", "map": "village", "col": 12, "row": 13, "facing": "down", "hiddenBy": ["attack_night", "attack_done"]},
        {"npcId": "hanna", "map": "village", "col": 7, "row": 13, "facing": "right", "hiddenBy": ["attack_night", "attack_done"]},
        {"npcId": "ria", "map": "village", "col": 17, "row": 14, "facing": "left", "hiddenBy": ["attack_night", "attack_done"]},
        {"npcId": "herbalist", "map": "village", "col": 14, "row": 31, "facing": "down", "hiddenBy": ["attack_night"]},
        {"npcId": "kael", "map": "village", "col": 23, "row": 9, "facing": "left", "requires": ["kael_mentor"], "hiddenBy": ["chapter1_done"]},
    ],
    "props": [
        {"sprite": "story_horse", "map": "village", "col": 16, "row": 10, "interactId": "feed_horse", "prompt": "여물 주기",
         "dialogue": "c1_horse_feed", "hiddenBy": ["attack_night", "attack_done"], "bob": True, "scale": 1.0},
        {"sprite": "story_trough", "map": "village", "col": 16, "row": 12, "interactId": "fill_trough", "prompt": "물 채우기",
         "dialogue": "c1_trough_fill", "hiddenBy": ["attack_done"]},
        {"sprite": "story_horse", "map": "village", "col": 16, "row": 10, "requires": ["horse_back"], "prompt": "쓰다듬기",
         "dialogue": "c1s_horse_found", "bob": True},
        {"sprite": "story_grave", "map": "village", "col": 21, "row": 8, "requires": ["family_buried"], "interactId": "family_graves",
         "prompt": "무덤 앞에 서기", "dialogue": "story_graves"},
        {"sprite": "story_grave_1", "map": "village", "col": 19, "row": 8, "requires": ["family_buried"], "interactId": "family_graves",
         "prompt": "무덤 앞에 서기", "dialogue": "story_graves"},
        {"sprite": "story_lantern", "map": "village", "col": 24, "row": 31, "requires": ["festival_eve"], "hiddenBy": ["attack_done"], "glow": True, "solid": False},
        {"sprite": "story_lantern", "map": "village", "col": 31, "row": 31, "requires": ["festival_eve"], "hiddenBy": ["attack_done"], "glow": True, "solid": False},
        {"sprite": "story_lantern", "map": "village", "col": 24, "row": 35, "requires": ["festival_eve"], "hiddenBy": ["attack_done"], "glow": True, "solid": False},
        {"sprite": "story_lantern", "map": "village", "col": 31, "row": 35, "requires": ["festival_eve"], "hiddenBy": ["attack_done"], "glow": True, "solid": False},
        {"sprite": "story_ribbon", "map": "forest", "col": 33, "row": 7, "activeQuest": "c1_trail", "interactId": "ria_ribbon",
         "prompt": "살펴보기", "dialogue": "c1_ribbon_found", "solid": False},
        {"sprite": "story_horse", "map": "forest", "col": 30, "row": 34, "activeQuest": "c1s_horse", "interactId": "lost_horse",
         "prompt": "다가가기", "dialogue": "c1s_horse_found", "bob": True},
    ],
}

def C(op, **kw):
    d = {"op": op}
    d.update(kw)
    return d

def line(speaker, text):
    return C("line", speaker=speaker, text=text)

CUTSCENES = [
    {"id": "c1_intro", "skippable": True, "cmds": [
        C("letterbox", count=1),
        C("place", actor="player", col=10, row=13, dir="down"),
        C("title", text="챕터 1\n잿더미의 마굿간", t=2.5),
        C("camera", actor="bram", t=0.6),
        C("dialogue", id="c1_bram_morning"),
        C("cameraReset"),
        C("letterbox", count=0),
    ]},
    {"id": "c1_attack", "skippable": True, "cmds": [
        C("letterbox", count=1),
        C("music", id="music_title"),
        C("tint", color="#141c3a99", t=1.2),
        C("place", actor="player", col=26, row=36, dir="up"),
        C("spawn", actor="ria", col=28, row=36, dir="left"),
        line("리아", "봐, " + N + "! 등불이 다 켜졌어. 내일 밤엔 우리 등불도 저기 있을 거야."),
        line(N, "...응."),
        C("wait", t=0.8),
        C("shake", t=0.5, power=0.15),
        line("", "북쪽에서 비명이 터진다."),
        C("fire", col=25, row=24, count=3),
        C("fire", col=36, row=22, count=2),
        C("fire", col=45, row=28, count=2),
        C("tint", color="#3a121eb0", t=1.0),
        C("music", id="music_boss"),
        C("emote", actor="player", text="!"),
        C("spawn", actor="bram", col=27, row=29, dir="down"),
        C("move", actor="bram", col=27, row=34, speed=4),
        line("브람", N + "! 해골들이 숲에서 넘어왔다! 리아 데리고 마굿간 쪽으로!"),
        line(N, "아저씨는요?!"),
        line("브람", "사람들 대피시키고 바로 간다. 가!"),
        C("move", actor="bram", col=12, row=30, speed=5, noWait=True),
        C("enemies", id="skel_warrior", col=27, row=27, count=3),
        C("enemies", id="skel_warrior", col=36, row=33, count=2),
        C("move", actor="ria", col=26, row=38, speed=3),
        C("despawn", actor="bram"),
        line("", "길이 막혔다. 해골들이 광장으로 몰려온다. 리아를 지켜야 한다!"),
        C("flag", id="attack_night"),
        C("letterbox", count=0),
    ]},
    {"id": "c1_stable", "skippable": True, "cmds": [
        C("letterbox", count=1),
        C("fadeOut", t=0.6),
        C("despawn", actor="ria"),
        C("place", actor="player", col=10, row=15, dir="up"),
        C("spawn", actor="ria", col=11, row=15, dir="up"),
        C("spawn", actor="bram", col=10, row=13, dir="down"),
        C("spawn", actor="hanna", col=8, row=14, dir="right"),
        C("fire", col=8, row=7, count=3),
        C("fire", col=13, row=8, count=2),
        C("camera", col=10, row=13, t=0),
        C("fadeIn", t=0.6),
        line("브람", "들어가! 건초 더미 밑으로. 무슨 소리가 나도 나오지 마라."),
        line(N, "아저씨도 같이—"),
        line("브람", N + "."),
        line("브람", "...넌 내 새끼다. 그러니까 말 들어."),
        C("fadeOut", t=0.4),
        C("place", actor="player", col=6, row=13, dir="right"),
        C("place", actor="ria", col=6, row=14, dir="right"),
        C("fadeIn", t=0.4),
        line("", "건초 틈 사이로, 마굿간 문 앞이 보인다."),
        C("spawn", actor="bargas", col=24, row=13, dir="left"),
        C("move", actor="bargas", col=13, row=13, speed=1.2),
        line("흑철의 바르가스", "용사의 핏줄 냄새가 난다. 이 마굿간이다."),
        line("브람", "여긴 말 냄새밖에 안 나. 돌아가."),
        line("흑철의 바르가스", "비켜라, 늙은이."),
        line("브람", "못 비켜."),
        C("shake", t=0.5, power=0.4),
        C("sfx", id="hit"),
        line("", "둔탁한 소리. 브람이 무릎을 꿇는다. 그래도 문틀을 붙잡은 손을 놓지 않는다."),
        line("브람", "...못... 비켜..."),
        C("shake", t=0.4, power=0.5),
        C("sfx", id="hit"),
        C("despawn", actor="bram"),
        line("", "브람이 쓰러진다."),
        line("리아", "(작게) ..." + N + ", 숨 쉬어. 소리 내지 마..."),
        C("move", actor="bargas", col=10, row=13, speed=1.0),
        line("흑철의 바르가스", "냄새는 이 근처에서 나는데."),
        C("move", actor="hanna", col=9, row=14, speed=3),
        line("한나", "여긴 아무도 없어요! 제발, 제발 가세요!"),
        line("흑철의 바르가스", "거짓말이 서툴군."),
        C("emote", actor="bargas", text="!"),
        line("", "바르가스의 시선이 건초 더미에 멈춘다. 리아가 먼저 뛰쳐나간다. 너를 숨긴 채로."),
        C("move", actor="ria", col=9, row=12, speed=4),
        line("리아", "나야! 여기 나밖에 없어!"),
        line("흑철의 바르가스", "...계집아이? 용사의 피는 아니군. 그래도 쓸모는 있겠어. 데려간다."),
        line("한나", "안 돼! 그 애는 안 돼!"),
        C("shake", t=0.3, power=0.3),
        line("", "한나가 바르가스의 팔에 매달린다. 검은 칼날이 한 번 번뜩인다."),
        C("sfx", id="hit"),
        C("despawn", actor="hanna"),
        line("", "한나가 쓰러진다."),
        line("리아", "아주머니!! 놔! 이거 놔!!"),
        C("move", actor="bargas", col=22, row=13, speed=1.1, noWait=True),
        C("move", actor="ria", col=21, row=13, speed=1.1),
        line("리아", N + "!! " + N + "—!!"),
        line(N, "리아!!"),
        C("move", actor="player", col=17, row=13, speed=5),
        C("face", actor="bargas", dir="left"),
        line("흑철의 바르가스", "...숨어 있던 쥐가 하나 더 있었군."),
        C("shake", t=0.6, power=0.9),
        C("sfx", id="player_down"),
        C("fadeOut", t=0.15),
        C("despawn", actor="bargas"),
        C("despawn", actor="ria"),
        C("place", actor="player", col=15, row=13, dir="down"),
        C("wait", t=1.2),
        line("", "......"),
        line("", "귀가 먹먹하다. 불타는 소리만 멀리서 들린다."),
        line("", "누군가의 발소리. 회색 망토 자락이 흐릿하게 다가온다."),
        line("카엘", "괜찮다, " + N + "."),
        line("카엘", "...이제 괜찮다."),
        C("wait", t=1.5),
        C("flag", id="attack_done"),
        C("flag", id="stable_burned"),
        C("flag", id="family_buried"),
        C("flag", id="kael_mentor"),
        C("unflag", id="attack_night"),
        C("clearProps"),
        C("tint", color="#00000000", t=0),
        C("heal"),
        C("travel", id="village", col=28, row=13, dir="down"),
    ]},
    {"id": "c1_wake", "skippable": True, "cmds": [
        C("letterbox", count=1),
        C("fadeOut", t=0),
        C("place", actor="player", col=28, row=13, dir="down"),
        C("spawn", actor="chief", col=29, row=15, dir="up"),
        C("title", text="사흘 뒤", t=2),
        C("fadeIn", t=1.5),
        line("촌장 모리", "깨어났구나... 사흘을 내리 잠만 잤다."),
        line("촌장 모리", "브람과 한나는... 마굿간 옆에 묻었다. 네가 깨면 직접 보내 주고 싶어 할 것 같아서."),
        line("촌장 모리", "그날 밤 불길 속에서 너를 업고 나온 기사가 있다. 카엘이라더군. 지금도 무덤 옆을 지키고 있다."),
        line(N, "......"),
        C("letterbox", count=0),
    ]},
    {"id": "c1_graves", "skippable": True, "cmds": [
        C("letterbox", count=1),
        line("", "브람. 한나."),
        line(N, "......"),
        line(N, "......"),
        line("", "등불을 같이 띄우자던 목소리. 국 식는다던 잔소리. '넌 내 새끼다.'"),
        line("", "아무것도 하지 못했다. 건초 더미 밑에서, 숨소리조차 참으면서."),
        line(N, "...나 때문에."),
        C("wait", t=1),
        line("", "손에 쥔 회색 천 조각. 그날 밤 브람의 손에서 나온 것이다. 마지막까지 붙잡고 있던 누군가의 옷자락."),
        C("move", actor="kael", col=22, row=9, speed=1),
        line("카엘", "울어도 된다."),
        line("카엘", "그다음에 일어서면 된다."),
        line("", "그날 이후 처음으로, 소리 내어 울었다."),
        C("fadeOut", t=1.5),
        C("wait", t=1.2),
        C("fadeIn", t=1.2),
        C("letterbox", count=0),
    ]},
    {"id": "c1_bargas_end", "skippable": True, "cmds": [
        C("letterbox", count=1),
        C("fadeOut", t=0),
        C("title", text="흑철 진영, 그날 밤", t=2),
        C("tint", color="#1a1020c0", t=0),
        C("fadeIn", t=1),
        line("", "쓰러진 바르가스가 피 섞인 웃음을 흘렸다."),
        line("흑철의 바르가스", "...용사의 핏줄이 제 발로 찾아오다니. 우스운 일이군."),
        line("흑철의 바르가스", "그 계집아이는 여기 없다. 처음부터... 우리에게 길을 알려 준 건, 너희 인간—"),
        C("shake", t=0.3, power=0.3),
        line("", "카엘의 검이 바르가스의 목을 꿰뚫었다."),
        line("카엘", "마족의 헛소리다. 귀 기울이지 마라."),
        line(N, "...리아는요? 리아는 어디 있어요!"),
        line("카엘", "포로 하나가 협곡 너머로 옮겼다고 불었다. 거기까지다."),
        C("fadeOut", t=1),
        C("tint", color="#00000000", t=0),
        C("wait", t=0.5),
        C("fadeIn", t=1),
        C("letterbox", count=0),
    ]},
    {"id": "c1_departure", "skippable": True, "cmds": [
        C("letterbox", count=1),
        C("fadeOut", t=0.6),
        C("place", actor="player", col=20, row=10, dir="up"),
        C("spawn", actor="kael", col=23, row=10, dir="left"),
        C("fadeIn", t=0.8),
        line(N, "다녀올게요. 아저씨, 아주머니."),
        line(N, "리아 데리고 올게요. 꼭."),
        line("카엘", "바위 협곡에 기사단이 있다. 리아를 찾으려면 그들의 힘이 필요하다."),
        line("카엘", "가자. 길은 내가 안다."),
        C("title", text="챕터 1 완료\n잿더미의 마굿간", t=3),
        C("letterbox", count=0),
    ]},
]

# Extra lines referenced only by the data.
EXTRA_DIALOGUES = [
    {"id": "c1_kael_fortress_report_followup", "lines": [
        {"speaker": "카엘", "text": "흑철 진영 문을 열 봉인 열쇠 조각, 모였나? 일요일 밤이다. 놈이 거기 있다."},
        {"speaker": "카엘", "text": "던전 안내원에게 '흑철의 바르가스' 레이드를 신청해라."}]},
    {"id": "stable_look", "lines": [{"speaker": "", "text": "브람의 마굿간. 건초 냄새와 말 냄새. 네가 자란 곳이다."}]},
    {"id": "stable_burned_look", "lines": [{"speaker": "", "text": "검게 탄 기둥만 남았다. 재 속에 반쯤 녹은 말편자가 보인다."}]},
]
