# -*- coding: utf-8 -*-
"""Chapter 2: 용사가 되는 길 (Docs/STORY.md section 5). Canyon map cells (60 rows x 48 cols): plaza ~ (24,22), upper terrace (24,6)."""
from ch1_story import quest, step, obj, items, C, line
N = "{name}"

def D(id, *lines):
    return {"id": id, "lines": [{"speaker": s, "text": t} for s, t in lines]}

CHAPTER = {"number": 2, "title": "용사가 되는 길",
           "summary": "바위 협곡의 기사단, 대사제의 임무, 검은 수호석. 그리고 등 뒤의 칼."}

QUESTS = [
    quest("c2_canyon", "2-1", "바위 협곡",
          "리아는 협곡 너머로 옮겨졌다. 바위 협곡 마을로 간다. (해골 숲 동쪽 끝)",
          [step("해골 숲을 지나 동쪽의 바위 협곡 마을로.", [obj("reach", "canyon", text="바위 협곡 마을에 도착하기")]),
           step("기사단 모집 게시판 앞의 기사단장.", [obj("talk", "leona", dialogue="c2_leona_first", text="북쪽 단상의 기사단장 레오나 만나기")])],
          chapter=2, requires=["c1_road"], reward={"xp": 600}),
    quest("c2_trial", "2-2", "기사단 시험",
          "기사단장 레오나의 세 관문. 힘, 인내, 동료.",
          [step("힘의 관문: 협곡 광산에서 실력을 증명하라.", [obj("dungeon", "*", 3, text="요일 던전 클리어")]),
           step("인내의 관문: 방패 든 해골을 꺾어라.", [obj("kill", "skel_shield", 12, text="해골 방패병 처치")]),
           step("동료의 관문: 기사단원 셋에게 인정받아라.", [
               obj("talk", "knight_dorn", dialogue="c2_knight_dorn", text="기사 돈에게 인정받기"),
               obj("talk", "knight_ivy", dialogue="c2_knight_ivy", text="기사 아이비에게 인정받기"),
               obj("talk", "knight_mo", dialogue="c2_knight_mo", text="기사 모에게 인정받기")])],
          chapter=2, requires=["c2_canyon"], giver="leona", offer="c2_leona_trial", turnIn="leona", turnInDialogue="c2_leona_pass",
          reward={"xp": 1800, "gold": 6000, "items": items(("ticket_protect", 1))}),
    quest("c2_priest", "2-3", "대사제의 부름",
          "견습 기사가 된 날, 왕국의 대사제가 협곡에 왔다.",
          [step("광장에 사람들이 모였다.", [obj("cutscene", "c2_orban", map="canyon", text="광장으로")])],
          chapter=2, requires=["c2_trial"], reward={"xp": 800, "setFlags": ["orban_met"]}),
    quest("c2_mine", "2-4", "협곡 광산 조사",
          "검은 수호석은 협곡 광산 깊은 곳 석실에 있다. 길을 찾아라. 리아의 소식도.",
          [step("협곡 광산의 던전을 뚫는다.", [obj("dungeon", "*", 5, text="요일 던전 클리어")]),
           step("광산 입구에서 붙잡힌 마족.", [obj("cutscene", "c2_prisoner", map="canyon", text="협곡 광장으로 돌아가기")])],
          chapter=2, requires=["c2_priest"], giver="orban", offer="c2_orban_mission", reward={"xp": 2500, "gold": 9000}),
    quest("c2_growth", "2-5", "석실 앞에서",
          "수호석 외곽 석실의 문지기는 지금의 실력으로는 무리다. 더 강해져라.",
          [step("힘을 기른다.", [obj("level", "", 28, text="레벨 28 달성 (석실 권장 레벨)"), obj("dungeon", "*", 15, text="요일 던전 클리어")]),
           step("축하연 전날 밤.", [obj("cutscene", "c2_letter", map="canyon", text="협곡 여관 앞에서 쉬기")])],
          chapter=2, requires=["c2_mine"], giver="kael", offer="c2_kael_growth", reward={"xp": 3000}),
    quest("c2_golem", "2-6", "바위 심장",
          "수호석을 지키는 석실 문지기, 바위 심장 골렘. (중간 레이드, 수·토·일)",
          [step("바위 심장 골렘을 쓰러뜨린다.", [obj("raid", "raid_golem", text="레이드: 바위 심장 클리어")])],
          chapter=2, requires=["c2_growth"], giver="leona", offer="c2_leona_golem", turnIn="leona", turnInDialogue="c2_leona_golem_done",
          reward={"xp": 5000, "gold": 15000}),
    quest("c2_grah", "2-7", "수호자 그라흐",
          "봉인 열쇠 조각으로 수호석 석실을 연다. 수호자 그라흐. (최종 레이드, 일요일)",
          [step("석실의 수호자 그라흐를 쓰러뜨린다.", [obj("raid", "raid_grah", text="레이드: 수호자 그라흐 클리어")]),
           step("수호석이 깨진 뒤.", [obj("cutscene", "c2_betrayal", map="canyon", text="협곡으로 돌아가기")])],
          chapter=2, requires=["c2_golem"], giver="orban", offer="c2_orban_grah", reward={"xp": 8000, "gold": 25000}),
    quest("c2_end", "2-끝", "잿빛 손",
          "왕국은 새로운 용사를 노래한다. 아무도 진실을 믿지 않는다.",
          [step("축제의 광장.", [obj("cutscene", "c2_aftermath", map="canyon", text="광장의 축제")])],
          chapter=2, requires=["c2_grah"], reward={"xp": 2000, "setFlags": ["chapter2_done"]}),
    # ---------------- 서브 ----------------
    quest("c2s_trader", "", "누리의 짐 수레",
          "협곡 상인 누리의 수레가 광산 길에서 해골들에게 털렸다.",
          [step("해골들이 가져간 물건을 되찾는다.", [obj("kill", "skel_miner", 10, text="해골 광부 처치")])],
          kind="sub", chapter=2, requires=["c2_canyon"], giver="trader", offer="c2s_trader_offer", turnIn="trader", turnInDialogue="c2s_trader_report",
          reward={"xp": 900, "gold": 4000, "items": items(("potion_hp", 10))}),
    quest("c2s_knight_letter", "", "기사 모의 편지",
          "기사 모가 고향 마을 어머니에게 보낼 편지를 부탁했다. 해골 숲 옆 작은 마을의 촌장에게 전하면 된다.",
          [step("편지를 촌장에게 전한다.", [obj("talk", "chief", dialogue="c2s_letter_chief", text="촌장 모리에게 편지 전하기")])],
          kind="sub", chapter=2, requires=["c2_trial"], giver="knight_mo", offer="c2s_letter_offer", turnIn="knight_mo", turnInDialogue="c2s_letter_report",
          reward={"xp": 700, "gold": 2500}),
]

WORLD = {
    "placements": [
        {"npcId": "leona", "map": "canyon", "col": 24, "row": 5, "facing": "down", "requires": ["chapter1_done"]},
        {"npcId": "knight_dorn", "map": "canyon", "col": 18, "row": 7, "facing": "right", "requires": ["chapter1_done"]},
        {"npcId": "knight_ivy", "map": "canyon", "col": 30, "row": 7, "facing": "left", "requires": ["chapter1_done"]},
        {"npcId": "knight_mo", "map": "canyon", "col": 26, "row": 8, "facing": "down", "requires": ["chapter1_done"]},
        {"npcId": "kael", "map": "canyon", "col": 27, "row": 24, "facing": "left", "requires": ["chapter1_done"], "hiddenBy": ["kael_betrayed"]},
        {"npcId": "orban", "map": "canyon", "col": 22, "row": 20, "facing": "down", "requires": ["orban_met"], "hiddenBy": ["kael_betrayed"]},
    ],
    "props": [
        {"sprite": "story_lantern", "map": "canyon", "col": 20, "row": 20, "requires": ["kael_betrayed"], "hiddenBy": ["chapter2_done"], "glow": True, "solid": False},
        {"sprite": "story_lantern", "map": "canyon", "col": 29, "row": 20, "requires": ["kael_betrayed"], "hiddenBy": ["chapter2_done"], "glow": True, "solid": False},
    ],
}

CUTSCENES = [
    {"id": "c2_orban", "skippable": True, "cmds": [
        C("letterbox", count=1),
        C("place", actor="player", col=24, row=25, dir="up"),
        C("spawn", actor="orban", col=24, row=21, dir="down"),
        C("spawn", actor="leona", col=21, row=22, dir="right"),
        C("spawn", actor="kael", col=26, row=25, dir="up"),
        C("title", text="챕터 2\n용사가 되는 길", t=2.5),
        line("대사제 오르반", "바위 협곡의 기사들이여. 그리고 새로 문장을 단 견습 기사여."),
        line("대사제 오르반", "봉인이 흔들리고 있다. 북쪽 땅의 마왕이 봉인을 깨고 있다."),
        line("대사제 오르반", "각 지역에 박힌 검은 수호석이 놈의 힘을 떠받치고 있다. 수호석을 깨야 놈을 약하게 할 수 있다."),
        line("대사제 오르반", "첫 수호석은 이 협곡 광산 깊은 곳에 있다."),
        C("move", actor="orban", col=24, row=23, speed=1.2),
        line("대사제 오르반", "...네가 해골 숲 옆 마을의 그 아이로구나. 친구가 끌려갔다지."),
        line("대사제 오르반", "그 아이가 수호석 근처에서 목격되었다는 보고가 있다."),
        line(N, "...리아가요?!"),
        line("대사제 오르반", "그래. 수호석을 깨는 길에 그 아이가 있다. 신께서 너를 이 길로 부르신 거다."),
        C("face", actor="orban", dir="right"),
        line("대사제 오르반", "카엘 경, 그대도 함께 가 주겠소?"),
        line("카엘", "...예, 대사제님."),
        line("", "대사제는 처음 보는 기사의 이름을 망설임 없이 불렀다."),
        line("기사단장 레오나", "(작게) ...잿빛 망토라. 처음 보는 문장이군."),
        C("letterbox", count=0),
    ]},
    {"id": "c2_prisoner", "skippable": True, "cmds": [
        C("letterbox", count=1),
        C("place", actor="player", col=30, row=25, dir="right"),
        C("spawn", actor="prisoner", col=33, row=25, dir="left"),
        C("spawn", actor="kael", col=31, row=23, dir="down"),
        C("spawn", actor="knight_dorn", col=34, row=24, dir="left"),
        line("기사 돈", "광산 입구에서 잡았습니다. 수호석 쪽에서 내려오던 놈입니다."),
        line("붙잡힌 마족", "...인간 꼬마. 해골 숲 옆 마을 아이냐."),
        line(N, "리아를 알아? 리아 어디 있어!"),
        line("붙잡힌 마족", "그 아이는... 우리가 해치려던 게 아니—"),
        C("move", actor="kael", col=32, row=25, speed=5),
        C("shake", t=0.3, power=0.3),
        C("sfx", id="hit"),
        C("despawn", actor="prisoner"),
        line("", "카엘의 검이 먼저 움직였다."),
        line(N, "...왜요! 뭔가 말하려고 했잖아요!"),
        line("카엘", "마족의 거짓말이다. 저런 말에 흔들리는 순간 네 목이 날아간다."),
        line("카엘", "리아를 찾고 싶으면 수호석까지 가라. 답은 거기 있다."),
        line("기사 돈", "(...단장님께 보고해야겠군.)"),
        C("letterbox", count=0),
    ]},
    {"id": "c2_letter", "skippable": True, "cmds": [
        C("letterbox", count=1),
        C("fadeOut", t=0.8),
        C("tint", color="#101830b0", t=0),
        C("place", actor="player", col=14, row=26, dir="up"),
        C("spawn", actor="kael", col=17, row=24, dir="left"),
        C("fire", col=16, row=25, count=1),
        C("fadeIn", t=1),
        line("", "축하연 전날 밤. 여관 앞 모닥불. 반쯤 잠든 눈에 카엘의 등이 보인다."),
        line("", "카엘이 품에서 편지 한 장을 꺼낸다. 붉은 밀랍 위의 문장. 대사제의 인장이다."),
        line("", "편지는 한 번 더 읽히고, 모닥불 속으로 들어간다."),
        line("카엘", "(작게) ...거의 다 왔다."),
        line("", "눈을 감는다. 꿈이었을 것이다. 분명 꿈이었을 것이다."),
        C("fadeOut", t=1),
        C("clearProps"),
        C("tint", color="#00000000", t=0),
        C("wait", t=0.5),
        C("fadeIn", t=1),
        C("letterbox", count=0),
    ]},
    {"id": "c2_betrayal", "skippable": True, "cmds": [
        C("letterbox", count=1),
        C("fadeOut", t=0),
        C("title", text="협곡 광산 깊은 곳, 수호석 석실", t=2),
        C("tint", color="#20102ac0", t=0),
        C("place", actor="player", col=24, row=24, dir="up"),
        C("spawn", actor="grah", col=24, row=21, dir="down"),
        C("spawn", actor="kael", col=27, row=26, dir="up"),
        C("fadeIn", t=1),
        line("", "쓰러진 그라흐 뒤로, 검은 수호석이 맥박치듯 빛난다. 손을 뻗자 돌이 울었다."),
        C("shake", t=1.2, power=0.6),
        C("sfx", id="rock_break"),
        line("", "수호석이 깨진다. 석실 천장이 무너지기 시작한다."),
        line("수호자 그라흐", "...가라! 전부 나가! 천장은 내가 받친다!"),
        line("", "그라흐가 무너지는 돌기둥을 등으로 받친다. 부하 마족들이 그 아래로 빠져나간다."),
        line("수호자 그라흐", "용사의 피... 네가 방금 무엇을 깼는지 아느냐..."),
        line(N, "......무슨, 소리야."),
        C("emote", actor="kael", text="..."),
        line("", "등 뒤에서 느린 박수 소리."),
        line("카엘", "수고했다, " + N + ". 역시 너였어. 수호석은 용사의 핏줄이 제 뜻으로 손을 대야만 깨지거든."),
        C("move", actor="kael", col=26, row=24, speed=1),
        line("카엘", "이제 남은 수호석은 네가 손만 대면 된다."),
        line(N, "카엘...? 무슨 말이에요."),
        line("카엘", "처음부터 말해 줄까. 해골 숲 옆 마을 마굿간에 용사의 핏줄이 산다고, 바르가스에게 알려 준 게 나다."),
        line("카엘", "그날 밤 나는 마을 밖에 있었다. 처음부터. 그 영감이 문 앞을 막고 쓰러지는 것도 봤지."),
        line("", "카엘이 망토 안감을 들춘다. 회색 천이 한 뼘, 찢겨 나가 있다."),
        line("카엘", "끝까지 놓지 않더군, 그 영감."),
        line(N, "......"),
        line("카엘", "리아가 끌려가는 것도 내버려 뒀다. 네가 멈추지 않고 걷게 하려고."),
        line("카엘", "네가 무너진 그날 밤에 손을 내민 것도, 칼을 쥐여 준 것도, 다 이걸 위해서였다."),
        line(N, "카엘——!!"),
        C("move", actor="player", col=25, row=24, speed=6),
        C("shake", t=0.4, power=0.5),
        C("sfx", id="hit"),
        C("place", actor="player", col=23, row=25, dir="right"),
        line("", "칼이 닿기도 전에 몸이 바닥에 처박혔다. 목 앞에 카엘의 칼끝이 멈춘다."),
        line("카엘", "죽이진 않는다. 너는 아직 쓸모가 있으니까."),
        line("카엘", "리아? 그 아이는 나도 모른다. 바르가스가 놓쳤거든. 찾고 싶으면 계속 걸어라. 늘 그랬듯이."),
        C("move", actor="kael", col=34, row=26, speed=2),
        C("despawn", actor="kael"),
        C("despawn", actor="grah"),
        C("fadeOut", t=1.2),
        C("flag", id="kael_betrayed"),
        C("leave", actor="kael"),
        C("tint", color="#00000000", t=0),
        C("wait", t=0.8),
        C("fadeIn", t=1),
        C("letterbox", count=0),
    ]},
    {"id": "c2_aftermath", "skippable": True, "cmds": [
        C("letterbox", count=1),
        C("place", actor="player", col=24, row=26, dir="up"),
        C("spawn", actor="orban", col=24, row=21, dir="down"),
        C("spawn", actor="leona", col=29, row=27, dir="left"),
        line("대사제 오르반", "협곡의 백성들이여! 새로운 용사가 첫 번째 수호석을 깨뜨렸다!"),
        line("대사제 오르반", "그리고 이 승리를 위해 성전기사 카엘 경이 석실에서 목숨을 바쳤다. 그의 이름을 기억하라."),
        line(N, "아니에요! 카엘은 죽지 않았어요! 그 사람이—"),
        line("대사제 오르반", "...용사여. 동료를 잃은 슬픔이 크구나. 쉬어라."),
        line("", "사람들의 박수 소리가 말을 덮는다. 누구도 돌아보지 않는다."),
        C("move", actor="orban", col=24, row=17, speed=1),
        C("despawn", actor="orban"),
        C("move", actor="leona", col=25, row=26, speed=1.5),
        line("기사단장 레오나", "잿빛 망토는 처음부터 이상했다."),
        line("기사단장 레오나", "대사제가 처음 보는 기사를 이름으로 부를 때부터. 포로를 그렇게 서둘러 벨 때부터."),
        line("기사단장 레오나", "네 말을 믿는다. 나 혼자뿐이라도."),
        line(N, "......"),
        line("", "두 번째로 무너졌다. 그리고 이번에는, 누가 손을 내밀기 전에 스스로 일어섰다."),
        line(N, "리아를 찾을 거예요. 그리고 카엘도."),
        line("기사단장 레오나", "그라흐의 부하들은 서쪽 마족 땅으로 갔다. 리아의 행방을 아는 건 어쩌면 그들이다."),
        C("shake", t=1.5, power=0.2),
        line("", "멀리서 땅이 갈라지는 소리가 들렸다. 수호석이 있던 협곡이 처음으로 메말라 가기 시작했다."),
        C("title", text="챕터 2 완료\n용사가 되는 길", t=3),
        C("letterbox", count=0),
    ]},
]

DIALOGUES = [
    D("c2_leona_first",
      ("기사단장 레오나", "해골 숲 쪽에서 온 아이로군. 바르가스를 쓰러뜨렸다는 소문은 들었다."),
      ("기사단장 레오나", "친구를 찾는다고? 기사단은 사사로운 일로 움직이지 않는다. 하지만 기사단원의 일이라면 다르지."),
      ("기사단장 레오나", "시험을 받아라. 통과하면 문장을 주겠다.")),
    D("c2_leona_trial",
      ("기사단장 레오나", "세 관문이다. 힘, 인내, 동료."),
      ("기사단장 레오나", "힘: 협곡 광산의 던전 세 곳을 뚫어라. 인내: 방패 든 해골 열둘을 꺾어라. 쉽게 깨지지 않는 놈들이다."),
      ("기사단장 레오나", "동료: 내 기사 셋에게 인정받아라. 칼만 잘 쓰는 놈은 기사가 아니다.")),
    D("c2_knight_dorn",
      ("기사 돈", "시험받는 녀석이군. 하나만 묻지. 넌 왜 칼을 드나."),
      (N, "...지키지 못한 사람이 있어서요. 이번엔 지키려고요."),
      ("기사 돈", "복수라고 했으면 떨어뜨렸을 거다. 통과.")),
    D("c2_knight_ivy",
      ("기사 아이비", "네 동료 기사 말인데, 잿빛 망토 그 사람."),
      ("기사 아이비", "어느 기사단 소속인지 물었더니 웃기만 하더라. 너는 알아?"),
      (N, "...저를 구해 준 사람이에요. 그것밖에 몰라요."),
      ("기사 아이비", "그렇구나. 은인을 믿는 건 좋은 거야. 통과.")),
    D("c2_knight_mo",
      ("기사 모", "어, 너 해골 숲 옆 마을에서 왔다며! 우리 엄마도 거기 근처 살아."),
      ("기사 모", "통과 통과! 대신 나중에 편지 하나만 부탁해도 돼?")),
    D("c2_leona_pass",
      ("기사단장 레오나", "세 관문을 다 넘었군. 오늘부터 바위 협곡 기사단의 견습 기사다."),
      ("", "레오나가 가슴에 기사단 문장을 달아 준다. 차가운 금속이 묵직하다."),
      ("기사단장 레오나", "그리고 카엘 경. ...잿빛 망토는 처음 보는군. 어느 기사단이오?"),
      ("카엘", "떠돌이입니다. 기사단은 오래전에 없어졌습니다."),
      ("기사단장 레오나", "...그렇소.")),
    D("c2_orban_mission",
      ("대사제 오르반", "협곡 광산은 언데드로 들끓고 있다. 석실로 가는 길을 열어라."),
      ("대사제 오르반", "광산을 오가는 마족이 있다면 사로잡아라. 리아라는 아이의 소식을 쥐고 있을지도 모른다.")),
    D("c2_kael_growth",
      ("카엘", "석실 앞의 문지기는 바위로 된 심장을 가진 거인이다. 지금의 너로는 한 대도 못 버틴다."),
      ("카엘", "레벨을 올리고, 장비를 갈아라. ...곧 끝난다, " + N + ". 곧.")),
    D("c2_leona_golem",
      ("기사단장 레오나", "석실 문지기, 바위 심장 골렘. 수요일과 토요일, 일요일에 광산 수문이 열린다."),
      ("기사단장 레오나", "골렘의 심장에 박힌 조각들이 수호석 석실의 열쇠라더군. 모아 오너라.")),
    D("c2_leona_golem_done",
      ("기사단장 레오나", "골렘이 쓰러졌다고? ...정말 해냈구나."),
      ("기사단장 레오나", "조심해라. 석실 안의 수호자는 마족 장수 그라흐다. 그리고... 등 뒤도.")),
    D("c2_orban_grah",
      ("대사제 오르반", "열쇠가 모였다면 석실이 열릴 것이다. 일요일, 달이 가장 높을 때."),
      ("대사제 오르반", "수호자를 쓰러뜨리고 네 손으로 수호석을 깨라. 반드시 네 손으로. 신의 뜻이다.")),
    D("c2s_trader_offer",
      ("협곡 상인 누리", "아이고, 광산 길에서 해골 광부 놈들이 내 수레를 통째로 털어 갔어!"),
      ("협곡 상인 누리", "열 놈만 혼내 주면 놈들이 숨겨 둔 짐이 나올 거야. 부탁해!")),
    D("c2s_trader_report",
      ("협곡 상인 누리", "됐다, 됐어! 물약 상자도 무사하네. 이건 사례야, 받아 둬!")),
    D("c2s_letter_offer",
      ("기사 모", "이거, 엄마한테 보낼 편지야. 해골 숲 옆 마을 촌장님께 드리면 전해 주실 거야."),
      ("기사 모", "기사 됐다고 자랑하는 내용이야. 뜯어보면 안 돼!")),
    D("c2s_letter_chief",
      ("촌장 모리", "모 녀석 편지로구나. 그 애 어머니가 매일 기다린다. 꼭 전하마."),
      ("촌장 모리", "그리고... 몸은 괜찮으냐. 눈빛이 많이 달라졌구나.")),
    D("c2s_letter_report",
      ("기사 모", "전해 줬어? 고마워! 엄마가 답장하면 너한테도 보여 줄게.")),
    D("leona_idle", ("기사단장 레오나", "검을 쥔 손보다 검을 거둘 줄 아는 손이 더 어렵다.")),
    D("knight_dorn_idle", ("기사 돈", "협곡 바람은 칼끝을 흔든다. 발부터 단단히 디뎌.")),
    D("knight_ivy_idle", ("기사 아이비", "단장님은 무뚝뚝해도 사람 보는 눈은 정확해.")),
    D("knight_mo_idle", ("기사 모", "엄마 보고 싶다...")),
    D("orban_idle", ("대사제 오르반", "신의 빛이 그대의 칼끝에 머물기를.")),
    D("prisoner_idle", ("붙잡힌 마족", "...")),
    D("grah_idle", ("수호자 그라흐", "...")),
]
