# -*- coding: utf-8 -*-
"""Generated costume-skin sheets (Flow, magenta) -> game sprite sheets in the original layout.

The skin is generated by repainting the reference atlas built from the shipped sheets, so every figure sits
in the cell it came from. Each cell is cut at the reference grid, reduced to the 64 px pixel grid, snapped to
the skin's own palette, and aligned to the original figure (feet line and body centre), so the warrior's
hand points (katana grip) and the walk/attack timing stay valid.

Usage:
  python3 process_skin.py warrior <generated.jpg> <skin id>  -> Assets/Resources/SilverWarrior/Skins/<id>/body.png, attack.png
  python3 process_skin.py mage <generated.jpg> <skin id>     -> Assets/Resources/Art/char_<id>_<dir>_<frame>.png
"""
import os, sys
import numpy as np
from PIL import Image
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from process_generated import key, ROOT, ART

CELL = 64
DIRS = ["down", "downside", "side", "upside", "up"]
FRAMES = ["idle0", "idle1", "walk0", "walk1", "walk2", "walk3", "attack", "hurt"]
# Reference atlas layout in 64-px-grid units (see the reference builders in this file's docstring).
WARRIOR_REF = (512, 683)   # body 8x5 at (0, 0), attack 6x5 at (0, 363)
MAGE_REF = (569, 320)      # 8x5 at (0, 0)


def palette_of(rgba, colors=56):
    opaque = rgba[rgba[..., 3] > 200][:, :3]
    sample = Image.fromarray(opaque[:: max(1, len(opaque) // 200000)].reshape(-1, 1, 3), "RGB")
    return sample.quantize(colors=colors, method=Image.Quantize.MEDIANCUT)


def cell_from(gen, ref_size, x, y, palette):
    """The generated cell at reference grid position (x, y) reduced to a hard-edged 64x64 pixel cell."""
    sx = gen.shape[1] / ref_size[0]
    sy = gen.shape[0] / ref_size[1]
    x0, y0 = round(x * sx), round(y * sy)
    x1, y1 = round((x + CELL) * sx), round((y + CELL) * sy)
    # Sample the centre of each source pixel block (the repaint keeps the 4x pixel grid), not an average:
    # averaging smears the 1-px outline and the eyes into the fill colours.
    piece = Image.fromarray(gen[y0:y1, x0:x1], "RGBA")
    sharp = np.asarray(piece.resize((CELL, CELL), Image.NEAREST)).copy()
    soft = np.asarray(piece.resize((CELL, CELL), Image.BOX))
    sharp[..., 3] = soft[..., 3]
    a = sharp
    alpha = np.where(a[..., 3] >= 120, 255, 0).astype(np.uint8)
    q = np.asarray(Image.fromarray(a[..., :3], "RGB").quantize(palette=palette, dither=Image.Dither.NONE).convert("RGB"))
    out = np.dstack([q, alpha]).astype(np.uint8)
    out[alpha == 0] = 0
    return outline(keep_main(out))


def outline(cell):
    """The warrior's 1-px dark rim: silhouette pixels take a deep shade of their own colour."""
    solid = cell[..., 3] > 0
    pad = np.pad(solid, 1)
    edge = solid & ~(pad[:-2, 1:-1] & pad[2:, 1:-1] & pad[1:-1, :-2] & pad[1:-1, 2:])
    out = cell.copy()
    rgb = out[..., :3].astype(np.float32)
    dark = np.clip(rgb * 0.32 + np.array([10, 8, 14]), 0, 255)
    lum = rgb.mean(axis=2)
    rim = edge & (lum > 60)
    out[..., :3][rim] = dark[rim].astype(np.uint8)
    return out


def keep_main(cell):
    """Drop stray specks (JPEG noise, a neighbour's sliver): keep the components of real size."""
    from scipy import ndimage
    solid = cell[..., 3] > 0
    lab, n = ndimage.label(solid)
    if n <= 1:
        return cell
    sizes = ndimage.sum(solid, lab, range(1, n + 1))
    big = max(sizes)
    for i, s in enumerate(sizes, 1):
        if s < max(6, big * 0.04):
            cell[lab == i] = 0
    return cell


def bbox(cell):
    ys, xs = np.nonzero(cell[..., 3] > 0)
    if len(ys) == 0:
        return None
    return xs.min(), xs.max(), ys.min(), ys.max()


def align(new, original):
    """Shift the new figure so its feet line and horizontal centre match the original figure's."""
    nb, ob = bbox(new), bbox(original)
    if nb is None or ob is None:
        return new
    dx = round((ob[0] + ob[1]) / 2 - (nb[0] + nb[1]) / 2)
    dy = ob[3] - nb[3]
    out = np.zeros_like(new)
    ys, xs = np.nonzero(new[..., 3] > 0)
    ty, tx = ys + dy, xs + dx
    ok = (ty >= 0) & (ty < CELL) & (tx >= 0) & (tx < CELL)
    out[ty[ok], tx[ok]] = new[ys[ok], xs[ok]]
    return out


def sheet(gen, ref_size, origin, original, cols, rows, palette):
    out = np.zeros((rows * CELL, cols * CELL, 4), np.uint8)
    for r in range(rows):
        for c in range(cols):
            orig = original[r * CELL:(r + 1) * CELL, c * CELL:(c + 1) * CELL]
            new = cell_from(gen, ref_size, origin[0] + c * CELL, origin[1] + r * CELL, palette)
            out[r * CELL:(r + 1) * CELL, c * CELL:(c + 1) * CELL] = align(new, orig)
    return out


def warrior(src, skin):
    gen = key(src, soft=1.4)
    pal = palette_of(gen)
    base = os.path.join(ROOT, "Assets", "Resources", "SilverWarrior")
    dst = os.path.join(base, "Skins", skin)
    os.makedirs(dst, exist_ok=True)
    body = np.asarray(Image.open(os.path.join(base, "body.png")).convert("RGBA"))
    attack = np.asarray(Image.open(os.path.join(base, "attack.png")).convert("RGBA"))
    Image.fromarray(sheet(gen, WARRIOR_REF, (0, 0), body, 8, 5, pal), "RGBA").save(os.path.join(dst, "body.png"))
    Image.fromarray(sheet(gen, WARRIOR_REF, (0, 363), attack, 6, 5, pal), "RGBA").save(os.path.join(dst, "attack.png"))
    print("wrote", dst)


def mage(src, skin):
    gen = key(src, soft=1.4)
    pal = palette_of(gen)
    for r, d in enumerate(DIRS):
        for c, f in enumerate(FRAMES):
            orig = np.asarray(Image.open(os.path.join(ART, f"char_mage_{d}_{f}.png")).convert("RGBA"))
            new = cell_from(gen, MAGE_REF, c * CELL, r * CELL, pal)
            Image.fromarray(align(new, orig), "RGBA").save(os.path.join(ART, f"char_{skin}_{d}_{f}.png"))
    print("wrote", skin, len(DIRS) * len(FRAMES), "frames")


if __name__ == "__main__":
    kind, src, skin = sys.argv[1:4]
    (warrior if kind == "warrior" else mage)(src, skin)
