#requires -PSEdition Desktop
param([Parameter(Mandatory=$true)][string]$Work, [string]$RecordName='registration')
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing
# Registration only: all creative edits are generated by ImageGen from the saved crops.
# Keep the full-resolution plate and every pixel outside the registered crop intact.
Add-Type -ReferencedAssemblies @([System.Drawing.Bitmap].Assembly.Location, [System.Drawing.Rectangle].Assembly.Location) -TypeDefinition @'
using System;
using System.Drawing;
using System.Drawing.Imaging;
using System.Drawing.Drawing2D;
using System.Runtime.InteropServices;
public static class RoadCropRegistration {
    public static void Apply(string input, string art, string output, int x, int y, int w, int h) {
        using (var source = new Bitmap(input))
        using (var generated = new Bitmap(art))
        using (var replacement = new Bitmap(w, h, PixelFormat.Format32bppArgb)) {
            using (var g = Graphics.FromImage(replacement)) {
                g.InterpolationMode = InterpolationMode.NearestNeighbor;
                g.PixelOffsetMode = PixelOffsetMode.Half;
                g.DrawImage(generated, new Rectangle(0,0,w,h));
            }
            var area = new Rectangle(x,y,w,h);
            var original = source.LockBits(area, ImageLockMode.ReadWrite, PixelFormat.Format32bppArgb);
            var revised = replacement.LockBits(new Rectangle(0,0,w,h), ImageLockMode.ReadOnly, PixelFormat.Format32bppArgb);
            var oldRow = new byte[w*4]; var newRow = new byte[w*4];
            const double feather = 160;
            for (int j=0; j<h; j++) {
                IntPtr op = IntPtr.Add(original.Scan0,j*original.Stride), np = IntPtr.Add(revised.Scan0,j*revised.Stride);
                Marshal.Copy(op,oldRow,0,oldRow.Length); Marshal.Copy(np,newRow,0,newRow.Length);
                for (int i=0; i<w; i++) {
                    double distance = feather;
                    if(x>0) distance=Math.Min(distance,i);
                    if(y>0) distance=Math.Min(distance,j);
                    if(x+w<source.Width) distance=Math.Min(distance,w-1-i);
                    if(y+h<source.Height) distance=Math.Min(distance,h-1-j);
                    double a=Math.Max(0,Math.Min(1,distance/feather)); a=a*a*(3-2*a);
                    for(int c=0;c<3;c++) oldRow[i*4+c]=(byte)Math.Round(oldRow[i*4+c]*(1-a)+newRow[i*4+c]*a);
                }
                Marshal.Copy(oldRow,0,op,oldRow.Length);
            }
            source.UnlockBits(original); replacement.UnlockBits(revised);
            source.Save(output,ImageFormat.Png);
        }
    }
}
'@
$repo = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
$record = @()
foreach ($entry in (Get-Content "$Work/crops.json" -Raw | ConvertFrom-Json)) {
    $id=$entry.id; $b=$entry.bounds
    $output="$repo/Assets/StreamingAssets/SurfaceWorld/$id.png"
    $artName=if($entry.art){$entry.art}else{"$id.png"}
    $art="$repo/Docs/World/HubRoadSources/refined/$artName"
    [RoadCropRegistration]::Apply("$Work/$id-before.png",$art,$output,$b[0],$b[1],$b[2],$b[3])
    # Lossless PNG packaging: discard the opaque alpha channel and compress.
    # No pixel colors or generated artwork change during this format conversion.
    'from PIL import Image; import sys; p=sys.argv[1]; im=Image.open(p); rgb=im.convert("RGB"); im.close(); rgb.save(p,optimize=True)' | & python - $output
    if ($LASTEXITCODE -ne 0) { throw 'PNG compression failed' }
    if ((Get-Item $output).Length -ge 96MB) { throw "Texture exceeds runtime file cap: $id" }
    $record += [ordered]@{id=$id;pixelBoundsXYWH=$b;source="Docs/World/HubRoadSources/refined/$artName";source_sha256=(Get-FileHash $art -Algorithm SHA256).Hash.ToLower();before_sha256=(Get-FileHash "$Work/$id-before.png" -Algorithm SHA256).Hash.ToLower();output_sha256=(Get-FileHash $output -Algorithm SHA256).Hash.ToLower();outsideCrop='unchanged';featherPixels=160;filter='nearest';geometry='unchanged'}
    Write-Output "$id registered"
}
$record | ConvertTo-Json -Depth 8 | Set-Content "$repo/Docs/World/HubRoadSources/refined/$RecordName.json" -Encoding UTF8
$manifestPath="$repo/Docs/World/map-hd-manifest.json"
$manifest=Get-Content $manifestPath -Raw | ConvertFrom-Json
foreach($entry in $record) {
    $asset=$manifest.assets | Where-Object id -eq $entry.id
    $asset.output_sha256=$entry.output_sha256
    $asset.road_patch="Docs/World/HubRoadSources/refined/$RecordName.json"
}
$manifest | ConvertTo-Json -Depth 12 | Set-Content $manifestPath -Encoding UTF8
