import fs from 'node:fs';
import path from 'node:path';
import { getGameData } from '../src/gamedata/loader';
import { clearXp, diffOf } from '../src/domains/dungeons/dungeonRules';
import { monsterXp } from '../src/domains/kills/killRules';
import { getPool } from '../src/db/pool';
import { setClockOverride } from '../src/utils/clock';
import { buildApp, resetDb, shutdown } from './helpers';
import { newHero, post } from './economyHelpers';

// Generated by the Unity player's -dotrpgHunting regression, not a second TS implementation.
const golden = JSON.parse(fs.readFileSync(path.join(__dirname, 'fixtures/hunting-balance.json'), 'utf8')) as {
  fields: { id: string; village: string; minLevel: number; maxLevel: number; fieldSpawns: { monsterId: string; points: number; level: number; xp: number; respawnSeconds: number }[] }[];
  dungeons: { id: string; clearXpFloor: number[]; clearXpF: number[] }[];
};
const app = buildApp();
beforeAll(resetDb);
afterAll(async () => { setClockOverride(null); await shutdown(); });
beforeEach(() => setClockOverride(() => new Date('2026-10-05T03:00:00Z')));

it('three fields per town cover levels 1 through 40 without gaps', () => {
  for (const town of ['village', 'canyon', 'winter']) expect(golden.fields.filter(f => f.village === town)).toHaveLength(3);
  expect(golden.fields[0]?.minLevel).toBe(1);
  expect(golden.fields.at(-1)?.maxLevel).toBe(40);
  golden.fields.slice(1).forEach((f, i) => expect(f.minLevel).toBe(golden.fields[i]!.maxLevel + 1));
});

it.each(golden.fields)('$id: authoritative spawn data matches the running C# client', field => {
  expect(getGameData().maps.get(field.id)?.instanced).toBe(false);
  expect(getGameData().economy.mapExtra.get(field.id)?.fieldSpawns).toEqual(field.fieldSpawns);
});

it.each(golden.fields)('$id: grants hunting XP to a hero with no dungeon clears', async field => {
  const h = await newHero(app);
  const spawn = field.fieldSpawns[0]!;
  const result = await post(app, h, '/kills', { map_id: field.id, monster_id: spawn.monsterId });
  expect(result.status).toBe(200);
  expect(result.body.data.granted_xp).toBe(spawn.xp);
  const rows = await getPool().query('SELECT monster_level, context, xp_granted, run_id FROM kill_log WHERE character_id = $1', [h.dbId]);
  expect(rows.rows).toEqual([expect.objectContaining({ monster_level: spawn.level, context: 'field', xp_granted: spawn.xp, run_id: null })]);
});

it.each(golden.dungeons)('$id: server clear XP matches the C# result on all difficulties', row => {
  const eco = getGameData().economy;
  const dungeon = eco.dungeons.byId.get(row.id)!;
  for (let tier = 0; tier < 4; tier++) {
    const diff = diffOf(eco, dungeon, tier)!;
    expect(clearXp(eco, dungeon, diff, 8)).toBe(row.clearXpF[tier]);
    let kills = 0;
    for (const room of dungeon.rooms) for (const g of room.groups) {
      const monster = eco.monsters.get(g.monsterId)!;
      if (!monster.noLoot) kills += g.count * monsterXp(eco, monster, 1 + diff.monsterLevel + g.levelOffset);
    }
    if (!dungeon.isRaid) {
      const field = golden.fields[[2, 4, 6, 8][tier]!]!;
      const fieldPerMinute = field.fieldSpawns[0]!.xp * 12;
      const dungeonPerMinute = (kills + clearXp(eco, dungeon, diff, 8)) * 60 / dungeon.referenceSeconds[tier]!;
      expect(dungeonPerMinute / fieldPerMinute).toBeGreaterThanOrEqual(1.799);
    }
  }
});

it('unknown maps and monsters outside a field remain rejected', async () => {
  const h = await newHero(app);
  expect((await post(app, h, '/kills', { map_id: 'winter_peak', monster_id: 'skel_gold' })).status).toBe(422);
  expect((await post(app, h, '/kills', { map_id: 'invented_field', monster_id: 'skeleton' })).status).toBe(422);
});
